### ISSUE TITLE
AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by deadseason** [lhlyu/tauri-chatgpt#27]
总是提示这个错误

**Comment by lhlyu** [comment]
我尝试了一些可能，但是没有重现这个错误

**Comment by deadseason** [comment]
![微信截图_20230627150600](https://github.com/lhlyu/tauri-chatgpt/assets/55622830/42171ae9-bb5d-4012-979e-44baf743d248)

**Comment by lhlyu** [comment]
可以贴一下配置吗，私密的信息可以打个码

**Comment by deadseason** [comment]
![微信截图_20230627154226](https://github.com/lhlyu/tauri-chatgpt/assets/55622830/37052c02-56fa-4d50-b0fe-02af59530c4b)

**Comment by deadseason** [comment]
github怎么私信呢。。。我想加你一下好友。。

**Comment by lhlyu** [comment]
你留个联系方式，我加你

**Comment by lhlyu** [comment]
我写这个应用更多是对tauri的实验，可能有很多问题，如果你真心想用类似的产品，可以试试`chatbox`

**Comment by deadseason** [comment]
我Q1138980537

**Comment by deadseason** [comment]
要不我加你吧☺️☺️
